version: '3'
services: 
  tracking-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment: 
      - PORT=3001
      - CORS_ORIGIN=${CORS_ORIGIN}

  tracking-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment: 
      - PORT=4000
      - CORS_ORIGIN=${CORS_ORIGIN}

  tracking-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment: 
      - PORT=8080
      - CORS_ORIGIN=${CORS_ORIGIN}

  caddy: 
    image: caddy/caddy:2.7.3-alpine
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
